export POSTGRESQL_ADDON_DB="b3t"
export POSTGRESQL_ADDON_HOST=127.0.0.1
export POSTGRESQL_ADDON_PASSWORD="b3t"
export POSTGRESQL_ADDON_PORT=5432
export POSTGRESQL_ADDON_USER="b3t"
export JWT_SECRET="MC4CAQAwBQYDK2VwBCIEIAomyszVLxZ2ImEcz/mXVDk3yhS5Z2Wullcta7BJL76v"
